name: pr_closed
on:
  pull_request:
    types: [closed]
jobs:
  remove-service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x
      - name: remove pr service
        run: ./scripts/remove-service.sh
        env:
          TAG: ${{ env.GITHUB_REF_SLUG }}
          GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
